// 전역 레이아웃 관련 파일
import Providers from "./providers";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

import SideTab from "@/components/SideTab";
import SubContainer from "@/components/SubContainer";
import Header from "@/components/Headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Discord Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex h-full">
            <aside className="w-[5%] bg-[#202225] h-screen">
              <SideTab />
            </aside>

            <div className="w-[95%] flex flex-col ">
              <Header />

              <main className="h-[95%] bg-[#303136] rounded-tl-2xl flex ">
                <div className="w-[20%]">
                  <SubContainer />
                </div>
                <div className="bg-[#363940] w-[80%]">{children}</div>
              </main>
            </div>
          </div>
          <div id="Authenticate-root"></div>
          <div id="modal-root"></div>
          <div id="SignUp-root"></div>
        </Providers>
      </body>
    </html>
  );
}
