// 전역 레이아웃 관련 파일

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

import SideTab from "@/components/SideTab";
import SubContainer from "@/components/SubContainer";
import Header from "@/components/Headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Discord Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          <aside className="w-[5%] bg-[#202225] min-h-screen">
            <SideTab />
          </aside>

          <div className="w-[95%] flex flex-col">
            <Header />

            <main className="h-[95%] bg-[#303136] rounded-tl-2xl flex">
              <div className="w-[20%] min-h-full">
                <SubContainer />
              </div>
              <div className="bg-[#363940] w-[80%] min-h-full">{children}</div>
            </main>
          </div>
        </div>
        <div id="Authenticate-root"></div>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
