version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: webrtc_db

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./webrtc_server
      dockerfile: Dockerfile
    image: psi7218/webrtc-backend:latest
    container_name: webrtc-backend
    ports:
      - "8080:8080"

    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/webrtc_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./webrtc_client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://thiscord.store/api/
        NEXT_PUBLIC_WS_URL: wss://thiscord.store/ws

    image: psi7218/webrtc-frontend:latest
    container_name: webrtc-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  mysql_data:
