// 전역 레이아웃 관련 파일

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-5 h-screen items-center justify-center`}
      >
        <div
          className="  mx-auto            /* 수평 중앙 정렬 */
            max-w-screen-3xl    /* 최대 너비를 제한 */
            my-auto 
            h-screen
            rounded-3xl       /* 둥근 모서리 */
            bg-black"
        >
          {children}
        </div>
      </body>
    </html>
  );
}
