name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # mysql 비밀번호를 .env 파일에 저장
      - name: Create .env file
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > .env

      # Docker 빌드 및 푸시
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build Spring Boot Project
        run: |
          cd webrtc_server
          chmod +x gradlew
          ./gradlew build -x test

      - name: Build and push Docker images
        run: |
          docker compose build
          docker compose push

      # EC2 배포.
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        timeout-minutes: 5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /opt/openvidu
            sudo su
            sudo sh -c echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > .env.db

            echo "Debug: .env.db 내용은 다음과 같습니다:"
            sudo cat .env.db

            sudo ./openvidu stop

            sudo docker rmi mysql:8.0
            sudo docker rmi psi7218/webrtc-frontend:latest 
            sudo docker rmi psi7218/webrtc-backend:latest 

            sudo docker pull mysql:8.0
            sudo docker pull psi7218/webrtc-frontend:latest
            sudo docker pull psi7218/webrtc-backend:latest

            (sudo ./openvidu restart > /dev/null 2>&1 &)

            echo "Deployment initiated successfully!!"
