name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Docker 빌드 및 푸시
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build Spring Boot Project
        run: |
          cd webrtc_server
          chmod +x gradlew
          ./gradlew build -x test

      - name: Build and push Docker images
        run: |
          docker compose build
          docker compose push

      # EC2 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Checking .env file..."
            ls -la /opt/openvidu/.env
            echo "Starting deployment..."
            cd /opt/openvidu
            sudo /usr/local/bin/docker-compose pull
            sudo -E ./openvidu restart
